### ISSUE TITLE
Doesn't seem to work with Elixir 1.3.4 and Erlang 19.1

### ISSUE THREAD

**Issue by aaronjensen** [lixhq/teamcity-exunit-formatter#3]
If I try to do anything w/ the module, it fails to load:

```
iex(3)> 08:49:02.001 [error] beam/beam_load.c(1376): Error loading module 'Elixir.TeamcityExunitFormatter':
  module name in object code is Elixir.TeamCityExUnitFormatter


08:49:02.001 [error] Loading of /Users/aaronjensen/Source/the-link/_build/test/lib/teamcity_exunit_formatter/ebin/Elixir.TeamcityExunitFormatter.beam failed: :badfile
```

**Comment by aaronjensen** [comment]
err, nevermind. I had the module name wrong.
